### ISSUE TITLE
the script saves skin 

### ISSUE THREAD

**Issue by insayd10** [boermansjo/ESX_HUD#1]
But when my char is login the game, saved skin not returns

**Comment by boermansjo** [comment]
My plan is to remove the outfit table and save the data into the default ESX column.

**Comment by HexagoneM** [comment]
I am looking forward to this project.

**Comment by insayd10** [comment]
> My plan is to remove the outfit table and save the data into the default ESX column.

I do that yester day i can pull request but got some problems like torso 1 torso 2

**Comment by insayd10** [comment]
And i maked female skins too, do you want pull request

**Comment by boermansjo** [comment]
You can always send a pull request.

**Comment by HexagoneM** [comment]
Make a pull request I will fix the torso bug 💃

**Comment by EGUltraTM** [comment]
Would be an nice idea to save it into the default esx table. Then it would be also plug and play for the clothes shop etc

**Comment by boermansjo** [comment]
Skin is now saved in the default esx table. Outfit is loaded correctly after login.
