### ISSUE TITLE
Issues with Clotheshop and Accessories !

### ISSUE THREAD

**Issue by Alevhovic** [boermansjo/ESX_HUD#10]
Hello @boermansjo,

#Not a real issue

First, thank you for the amazing work.

I have some question : 

- In our "server.cfg", we don't need to start "esx_skin" ?
- Same for "skinchanger" ?

- Is it compatible with esx_clotheshop // esx_eden_clotheshop ?

- What do you think / recommend about this start order :

start skinchanger
start skincreator
?start esx_skin? 
start esx_identity
...
start esx_clotheshop

Thanks for you answer and you work again !

**Comment by XvenDeR** [comment]
you dont need esx_skin.

**Comment by boermansjo** [comment]
Hi,
With this version you don't need esx_skin.

- Skinchanger is still needed.
- It is compatible with esx_clotheshop (or any other script that was using esx_skin)
It still has a few bugs. But they will be fixed this week.
- The start order is not very important. The script is only called when it is needed. (Reason why the screen is clean when entering the identity data)

**Comment by Alevhovic** [comment]
Ok i try this.

For "classic" ESX server, we have to modify those files :

- esx_accessories --> resource.lua
- esx_jobs --> resource.lua
- esx_barbershop --> resource.lua
- esx_clotheshop --> resource.lua
- esx_tattoshop --> resource.lua

Thanks again for your work and your answer guys.

**Comment by Alevhovic** [comment]
Doesn't work with esx_accessories / esx_clotheshop. The selection menu doesn't show... 

Any idea why ?

Informations :

# Start order
- skinchanger
- skincreator
[...]
- es_extended
[...]
- esx_clotheshop
- esx_accessories

# Artifacts

Last version
Same for Essentialmode, es_extended...

**Comment by Alevhovic** [comment]
Fixed, that's was my bad. Your work is awesome.

@boermansjo

**Comment by x20i** [comment]
how did you get this working i have the same problem

**Comment by Dexterin0** [comment]
Should work just fine, got it working as well after some adjustments. :) 
BTW great to hear you will add a simpler way to add clothes, I thought about that as well but my skills are not enough yet, working on that. :)

**Comment by MunkeyyJ** [comment]
Im sorry to reply on an closed issue but how was your issue resolved as you didn't say, I am struggling to get it working
I have removed esx_skin and only have Skinchanger and skincreator but using the esx_clotheshop, the menu won't open

**Comment by boermansjo** [comment]
You will have to change the dependencies :

`dependencies { 'es_extended', 'esx_skin' }`

into

`dependencies { 'es_extended', 'skincreator' }`

**Comment by MunkeyyJ** [comment]
I have changed that on everything and the only way I got it to show was edit the clotheshop and trigger event hud:load which shows fine but the moment I select the clothings tab my character resets to default dan

hopefully I've missed something and you can help as my head and the brickwall of code have met haha

**Comment by boermansjo** [comment]
Not sure what you are trying to add, but the latest version you don't need the hud:load anymore. 
It should work fine out of the box.
And yes, there is still a small bug with the clothing tab using the clotheshop. It will be fixed soon.

**Comment by CrazeDE** [comment]
How do I receive the HUD from the Skin Creator in the Clothes shop too and how would I go about the issue that it loads the regular freemode male whenever I open the clothes shop?

**Comment by Alevhovic** [comment]
This is not what we are doing here... We still use the clotheshop menu.
