### ISSUE TITLE
cant get the new menu ui to show

### ISSUE THREAD

**Issue by x20i** [boermansjo/ESX_HUD#11]
after reading over all the issues and doing everything and trying everything you have told others I am still unable to get the new menu UI to show

I have no errors I have all the needed files and have fully removed esx_skins from our server

**Comment by Dexterin0** [comment]
Strange. 
For me it works just fine, I had issues at start as well. Change the hud_load and remove esx_skin dependencies, it should work. 
For now it only shows when you create a new character or type in chat /skin.
