### ISSUE TITLE
Every time players connects he can change his look

### ISSUE THREAD

**Issue by SpecialStos** [boermansjo/ESX_HUD#13]
Hey,

got this whole thing working with all cloth shops and outfits without an issue. Only issue is that every time a player connects he gets the box that asks him to redo his character. I tried making it check from the database if he has already an identifier and if he does that means he is an existing player and will close the UI. Seems like it still doesn't like that. Could you help me out? 

Thanks for reading,
SpecialStos

P.S: Thanks for your edits, they are awesome!

**Comment by boermansjo** [comment]
Maybe it is an other script that is giving you this option.
This skincreator will never ask you to redo the character.

**Comment by HexagoneM** [comment]
Would you mind sharing with us ? @SpecialStos

**Comment by boermansjo** [comment]
I have just seen the issues with SteamID's. Maybe that is now the problem.
This scripts uses ESX. I cannot fix that in this script. The people of FiveM needs to find a new way or we should create a new server base.

**Comment by boermansjo** [comment]
Updated the script to use the latest ESX 1.2.
No more steamID's 👯
