### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by XvenDeR** [boermansjo/ESX_HUD#15]
Project abandoned?

**Comment by boermansjo** [comment]
I don't have time for now sorry :/
I will try to update this project soon.

**Comment by amerem3** [comment]
What still needs to be done? Just clothing ids or more?

**Comment by boermansjo** [comment]
update female options
clothing id
fixing some bugs with the old esx_skin (So that old shop menus still work)

**Comment by MrQuestionZ** [comment]
Any update? Or still no free time over :) (know the feeling)

**Comment by boermansjo** [comment]
> Any update? Or still no free time over :) (know the feeling)

I have my new computer now. Tomorrow I will add some updates and will do my best to finish this.

**Comment by GMA950** [comment]
> 
> 
> > Any update? Or still no free time over :) (know the feeling)
> 
> I have my new computer now. Tomorrow I will add some updates and will do my best to finish this.

What a time to be alive WE ALL LOVE YOU!

**Comment by boermansjo** [comment]
finally some updates 🎉
