### ISSUE TITLE
skincreator with esx_clotheshop

### ISSUE THREAD

**Issue by playazkah18** [boermansjo/ESX_HUD#19]
Hi,

How can I do that open the skincreator menu if I going to a 'Clothes Shop' instead of the default skin menu?

**Comment by XvenDeR** [comment]
I think the same way as in esx_identity

**Comment by playazkah18** [comment]
What do you mean with the esx_identity? That use the skincreator menu too or what?

**Comment by HurtsAsHell** [comment]
Hi, is there anyone that know how to modify the menù?
I like the idea of @playazkah18 but searching in esx_clotheshop/client i didn't find nothing...

**Comment by LuLisTaken** [comment]
You can use hud:loadMenu to open menu

**Comment by HurtsAsHell** [comment]
@LuLisTaken i need to add this in the client?

**Comment by XvenDeR** [comment]
> @LuLisTaken i need to add this in the client?

yes

**Comment by HurtsAsHell** [comment]
How could know if player have pressed "yes" of "no" to save his character?
For esx_skin is 
```
elements = {
				{label = _U('no'), value = 'no'},
				{label = _U('popupYes'), value = 'yes'}
		}
```

**Comment by HurtsAsHell** [comment]
thanks @XvenDeR

**Comment by boermansjo** [comment]
This script does not support the old menu.
My plan now is to get esx_skin running too.

**Comment by Valkatastz** [comment]
Dude, I just went through all your code... I am not actually surprised why it doesn't work :D ... You are overriding it ... What I can see is pretty much copy/paste from esx_skin stuff and referring back to it and requesting data from esx_skinchanger. The way you are working is far wrong. Focus on getting rid off of using too much connections and requests or combine them together. Other solution that can help you with is to make a better html menu to esx_skin which would be by far the easiest solution.

**Comment by boermansjo** [comment]
The way esx_skin is made does not allow this kind of add-on. You can't have 2 on spawn functions doing their own thing. That is why most of the skin functions are in there. But as you can see I removed a lot of them.
I used the original code as guide and continued on that base. But now I try to start from scratch.
Also if you have a better solution. Please share with everyone.
