### ISSUE TITLE
Skinchanger default skin and after a few minutes you have created

### ISSUE THREAD

**Issue by Luis26x** [boermansjo/ESX_HUD#22]
“Zaphosting server”
Hello again, ask.
when install,
1, skinchanger
2, skincreator
3, esx_np_skinshop
Should we deactivate something?

Everything is working smoothly, only when you enter the game you get the default skin and after a few minutes you have created. Is there a way to avoid that?

[https://forum.cfx.re/uploads/default/optimized/4X/f/3/d/f3dec82cc4f66f805a4241357a87f83cb7a5c2f7_2_1035x186.jpeg]

https://www.youtube.com/watch?v=wBCuDpmb27Q&feature=emb_logo

**Comment by Neo1030** [comment]
I have the same issue.
I try to debug it, the problem for me, is when you load another time the skin (clothes shop, etc) that reset the script...

**Comment by boermansjo** [comment]
This problem has been fixed. WARNING : not tested using esx_skin !!! feel free to test please
