### ISSUE TITLE
The skinchanger didn't affect the player skin, and the create button didn't work

### ISSUE THREAD

**Issue by Sziszkaaa675** [boermansjo/ESX_HUD#23]
I tried to put the code into the esx indentity, but I'm not sure where I can put it. This can be the problem, or something that I missed?

**Comment by ZockerBoysHD** [comment]
Then u renamed the skincreator ressource to something other than 'skincreator' and the nuicallbacks dont work anymore.

**Comment by boermansjo** [comment]
I removed the old esx_skin menu for now to keep everything clean.
Using this with esx identity is no longer a problem
