### ISSUE TITLE
scrolling is bugged

### ISSUE THREAD

**Issue by wolgix** [boermansjo/ESX_HUD#3]
Sometimes can scroll in the menu, but sometiems i cant.

**Comment by boermansjo** [comment]
Yes, the scroll is very bugged. This is on the list.

**Comment by King-Tut-Tut** [comment]
You can fix this by changing:
SetNuiFocus(enable)
To:
SetNuiFocus(enable, enable)

The second parameter enables the "real" mouse cursor. You can remove anything related to the "cursor"-element in both HTML and JS after doing this.

**Comment by boermansjo** [comment]
That fixes a lot of problems. I have changed the html too. Once I upload it here, I will close this issue.

**Comment by wolgix** [comment]
nice, i have 1 more problem, when choose the skin, and save it works, but when i reconnect, i have default skin again :/

**Comment by XvenDeR** [comment]
Because you dont load from skincreator table in db.

**Comment by boermansjo** [comment]
I am changing the saving part so that it works with skinchanger. Plan is that this script just replaced the esx_skin. 
But fiveM has connection problems. I hope tomorrow I can test again.

**Comment by wolgix** [comment]
cool <3

**Comment by boermansjo** [comment]
Issue fixed
