### ISSUE TITLE
do i need to remove esx_skin ?

### ISSUE THREAD

**Issue by YInfeRnal** [boermansjo/ESX_HUD#32]
do i need to remove esx_skin ?

**Comment by YInfeRnal** [comment]
and skinchanger

**Comment by YInfeRnal** [comment]
do i need to remove esx_skin or skinchanger to use this scrip?

**Comment by boermansjo** [comment]
Hi, skinchanger is needed for this script. You don't have to remove esx_skin.
But you will have to modify a few bits so that you don't have 2 menu's.

**Comment by YInfeRnal** [comment]
hello thanks you
can we do this work with esx_barbershop??
skincreator not esx_skin

**Comment by YInfeRnal** [comment]
or any other barbershop?
