### ISSUE TITLE
Vanilla skinchanger still showing up

### ISSUE THREAD

**Issue by Dexterin0** [boermansjo/ESX_HUD#8]
Pretty new to this LUA and GTA scripting, slowly getting the hang of it. 
Had this UI parked now, tried yours and I cant seem to get it working as it always calls the vanilla esx skin changer, although I removed esx_skin and skinchanger from the server.cfg. 
This is due to its roots in the vanilla esx menu I guess. 

Isn't there something missing to call this skinchanger instead of the vanilla ui or am I missing something?

**Comment by boermansjo** [comment]
Hi,
You still need skinchanger. My script only replace esx_skin.
This is still in production. Not ready for a public server. But for a Dev it can be fun.
If the menu is still showing, make sure the cache is deleted. (You can also check the console when the server is loading. If you see any esx_skin some other script may have this in his dependency)

**Comment by joyntie** [comment]
I stopped esx_skin in through the console and could open the new hud with the command then, when I tried to join esx_jobs couldn't load anymore. Im getting closer. haha

Currently doing some try and error, somehow it loaded esx_skin even if I took it out of the server.cfg and out of the cache lol. I removed the folder for now and as Im using the clothingshop I will change that line now. 


Thanks!

**Comment by joyntie** [comment]
Removed esx_skin from esx_jobs and esx_barbershop as well.

**Comment by boermansjo** [comment]
If this gives to many problems, I will rename the resource into esx_skin. Then we don't have to change all the dependencies. Those lines are a curse for when you want to make a new script :D

**Comment by joyntie** [comment]
Actually thats fine, could have realized that myself its called elsewhere. 
I had some more with it inside, so for a final release changing the ressource name might be a good idea.

Got it cleared out now, now more vanilla esx_skin. :P Running the command now works fine, opening the menu when first spawned is not included yet or dont I have to change the one line from the other issue?

**Comment by boermansjo** [comment]
It is included. I test this with esx_identity.
There is a line like this : `TriggerEvent('esx_skin:openSaveableMenu', myIdentifiers.id)`
So I don't know what you use to create the name and stuff. (You may not use any...)
For the record, this version still has the vanilla esx_skin menu. This is so that your barbershop or jobs still works.

**Comment by joyntie** [comment]
Got it working thanks. :)

Yes thats the good thing! Thats why I took yours, to keep functionality.

Good work.

**Comment by boermansjo** [comment]
Nice. You will experience some crazy stuff for now. It will look like you have 2 skins when you use the clotheshop. Still debugging this.

**Comment by joyntie** [comment]
Haha okay, if I see something I'll write it down and see what I can do as well. 

But with my vanilla esx_skin this happened as well....that and the look of the ui were the reason I wanted to get rid of it.

**Comment by kydsvandy** [comment]
So I change my esx_identity TriggerEvent('hud:loadMenu') to TriggerEvent('esx_skin:openSaveableMenu', myIdentifiers.id) now it opens the default skincreator when you /register 
![Screenshot (951)](https://user-images.githubusercontent.com/54919706/65288859-e9695c00-db7a-11e9-8d14-df13c61e1558.png)

**Comment by boermansjo** [comment]
You probably still have esx_skin that is loading.
Make sure all dependencies are changed. If one still has esx_skin in it, it will be loaded.
You can check the console to see if it is loaded or not.

**Comment by kydsvandy** [comment]
I stop my esx_skin.. but still showing

**Comment by boermansjo** [comment]
That is the problem. Stopping the script is not enough. If you have any other script that was using that it will load esx_skin. (Even if you didn't include it in the server.cfg)
You probably have an other script (like esx_clotheshop) where you have a dependency. 
Dependencies will load the script if it is in the resource folder. So best way to find out is to remove the esx_skin folder and run your server.  Don't forget to clear the cache also.

**Comment by kydsvandy** [comment]
oh yeah esx_jobs still use esx_skin maybe that's why?

**Comment by kydsvandy** [comment]
yeah it work I change the dependencies of the esx_jobs to skincreator

**Comment by kydsvandy** [comment]
but now everytime I join I have an npc skin for some reason..

**Comment by kydsvandy** [comment]
yep changing the dependencie of esx_jobs from esx_skin to skincreator.. make you spawn as npc everytime you join the server.

**Comment by Dexterin0** [comment]
Make sure to keep skinchanger, remove esx_skin, search via notepad for all esx_skin dependencies, remove them, optional delete the outfit tables in your database and you should be good to go, for me it worked and I have lots of smaller changes in esx and lots of additions.

**Comment by kydsvandy** [comment]
> Make sure to keep skinchanger, remove esx_skin, search via notepad for all esx_skin dependencies, remove them, optional delete the outfit tables in your database and you should be good to go, for me it worked and I have lots of smaller changes in esx and lots of additions.

but removing esx_skin on the dependecies of esx_jobs make every player invisible everytime they join the server.

**Comment by blurryrox** [comment]
I am just guessing here but maybe it has issues after removing the esx_skin folder because of this?
server/main.lua : Line 22
`local file = io.open('resources/[esx]/esx_skin/skins.txt', "a")`

**Comment by ighorplays** [comment]
hello, I'm using this script on my server for the community, but I face a problem that I'm finding a bag, without esx_skin in the work they don’t put on their uniforms / take the burden out of the work, sorry my English from the translator, would you have any idea to solve this problem?

**Comment by EnerGonix** [comment]
I get it to work but im using esx_np_skinshop v2 and the skin goes back to the default one!

Can someone help ?

**Comment by Squad3tm** [comment]
Might help people, if you're using another character creator, make sure you uncomment  "onFirstSpawn" in esx_skin to prevent the default skin creator popping up.

**Comment by boermansjo** [comment]
If you are using my version, you don't need this. I replace that function. All you have to do was remove the esx_skin folder.
But they made some changes in the recent version. Not sure if want to spend time in fixing all this if FiveM keeps blacklisting ESX...

**Comment by boermansjo** [comment]
Yes it is still a good input. Most people are trying to add this and keep esx_skin also...
This will not work. The original script was kind of a mess mixing both scripts. I never spend much time in making it a stand-alone version. If someone wants to try, I can always help.

**Comment by MovingTarget123** [comment]
Hello,
Awesome that you redid the script because the original one I couldn't get to work at all. Anyways, when I enter shop it resets my ped, and opens the default esx_skin customization. I deleted esx_skin folder, change the dependency on esx_clotheshop. Could it be esx_identity starting the default esx_skin window?

**Comment by boermansjo** [comment]
I removed the complete old esx_skin menu.
This version now only do the creation part. Using it may break something

**Comment by moquino** [comment]
iam using skincreator but when i join i found the default skin menu and skincreator menu, now i want use skincreator only in FirstSpwan and esx_skin for clothes shop, how to do that ? 

note:
- i try remove esx_skin folder and still show and all other script that depend on it stopped
- i try to remove 
RegisterNetEvent('esx_skin:openSaveableMenu')
AddEventHandler('esx_skin:openSaveableMenu', function(submitCb, cancelCb)
  OpenSaveableMenu(submitCb, cancelCb, nil)
end)
and default skin menu not visible but when i try to change clothes in shop and press enter to buy and i choose no the clothes i changed save when i press no and can move with new clothes.
can some one help me to fix it ?

**Comment by domysalv** [comment]
@moquino could you solve this? @boermansjo any way to do this?

**Comment by Codyshep** [comment]
my menu wont save/close

**Comment by GeneralBondi** [comment]
> iam using skincreator but when i join i found the default skin menu and skincreator menu, now i want use skincreator only in FirstSpwan and esx_skin for clothes shop, how to do that ?
> 
> note:
> 
> * i try remove esx_skin folder and still show and all other script that depend on it stopped
> * i try to remove this code from esx_skin/client.lua
>   RegisterNetEvent('esx_skin:openSaveableMenu')
>   AddEventHandler('esx_skin:openSaveableMenu', function(submitCb, cancelCb)
>   OpenSaveableMenu(submitCb, cancelCb, nil)
>   end)
>   and default skin menu not visible but when i try to change clothes in shop and press enter to buy and i choose no the clothes i changed save when i press no and can move with new clothes.
>   can some one help me to fix it ?

You have to go to "esx_skin" and change line #14
local FirstSpawn = True

a

local FirstSpawn = nil

With that you will no longer see the esx_skin at the beginning
