### ISSUE TITLE
esx_hud not working...

### ISSUE THREAD

**Issue by SliderKP** [boermansjo/ESX_HUD#9]
when i try to change the ped, hair, clothes, or anything, not working:
http://puu.sh/EaUxC/efa3150462.jpg

When i use the buttom "finish", and then press Yes, not closing...

http://puu.sh/EaUxW/afbd2a8ead.jpg

**Comment by XvenDeR** [comment]
Are you sure that you using latest version?

**Comment by SliderKP** [comment]
yes is the last version.

**Comment by Cactusje** [comment]
Same issue here

**Comment by ZockerBoysHD** [comment]
same issue for me.

**Comment by boermansjo** [comment]
This should all be working now
